const path = require('path');

module.exports = {
  apps: [
    // ========== CampFlow (現有) ==========
    {
      name: 'campflow-api',
      cwd: '/home/yu/projects/campflow/apps/api',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      log_file: '/home/yu/logs/campflow-api.log',
      out_file: '/home/yu/logs/campflow-api-out.log',
      error_file: '/home/yu/logs/campflow-api-error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'campflow-web',
      cwd: '/home/yu/projects/campflow/apps/web',
      script: 'node_modules/.bin/next',
      args: 'start --port 3102',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
      },
      log_file: '/home/yu/logs/campflow-web.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },

    // ========== InnSaaS (新增) ==========
    {
      name: 'inn-api',
      cwd: '/home/yu/projects/inn-saas/apps/api',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        PORT: 3101,
        DATABASE_URL: 'postgresql://postgres:InnSaas_2026_NewPass@localhost:5433/inn_master',
        REDIS_URL: 'redis://localhost:6379/1',
        JWT_SECRET: 'inn-saas-secret-key-2026',
      },
      log_file: '/home/yu/logs/inn-api.log',
      out_file: '/home/yu/logs/inn-api-out.log',
      error_file: '/home/yu/logs/inn-api-error.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'inn-web',
      cwd: '/home/yu/projects/inn-saas/apps/web',
      script: '.next/standalone/apps/web/server.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        PORT: 3102,
        NEXT_PUBLIC_API_URL: 'https://api.inn.yu.dopay.biz',
      },
      log_file: '/home/yu/logs/inn-web.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'inn-admin',
      cwd: '/home/yu/projects/inn-saas/apps/admin',
      script: '.next/standalone/apps/admin/server.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        PORT: 3103,
        NEXT_PUBLIC_API_URL: 'https://api.inn.yu.dopay.biz',
      },
      log_file: '/home/yu/logs/inn-admin.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'inn-linebot',
      cwd: '/home/yu/projects/inn-saas/apps/line-bot',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: {
        NODE_ENV: 'production',
        PORT: 3104,
        REDIS_URL: 'redis://localhost:6379/1',
        API_BASE_URL: 'http://localhost:3101',
        LINE_CHANNEL_ACCESS_TOKEN: '',
        LINE_CHANNEL_SECRET: '',
      },
      log_file: '/home/yu/logs/inn-linebot.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],

  // 部署配置
  deploy: {
    production: {
      user: 'yu',
      host: 'localhost',
      ref: 'origin/main',
      repo: '',
      path: '/home/yu/projects/inn-saas',
      'post-deploy': 'npm install && npm run build && pm2 reload ecosystem.config.js --env production',
    },
  },
};
