inn.yu.dopay.biz {
    encode gzip
    reverse_proxy localhost:3102
    log {
        output file /var/log/caddy/inn-saas.log {
            roll_size 10MB
            roll_keep 10
        }
    }
}

admin.inn.yu.dopay.biz {
    encode gzip
    reverse_proxy localhost:3103
    log {
        output file /var/log/caddy/inn-saas-admin.log {
            roll_size 10MB
            roll_keep 10
        }
    }
}

api.inn.yu.dopay.biz {
    encode gzip
    reverse_proxy localhost:3101
    log {
        output file /var/log/caddy/inn-saas-api.log {
            roll_size 10MB
            roll_keep 10
        }
    }
}

bot.inn.yu.dopay.biz {
    encode gzip
    reverse_proxy localhost:3104
    log {
        output file /var/log/caddy/inn-saas-bot.log {
            roll_size 10MB
            roll_keep 10
        }
    }
}
