
# Demo3 測試民宿
demo3.inn.yu.dopay.biz {
    encode gzip
    reverse_proxy localhost:3102
    log {
        output file /var/log/caddy/inn-saas-demo3.log {
            roll_size 10MB
            roll_keep 10
        }
    }
}

admin.demo3.inn.yu.dopay.biz {
    encode gzip
    handle /api/* {
        reverse_proxy localhost:3101
    }
    handle {
        reverse_proxy localhost:3103
    }
    log {
        output file /var/log/caddy/inn-saas-demo3-admin.log {
            roll_size 10MB
            roll_keep 10
        }
    }
}